on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action steps
      id: hello
      uses: ops-ml/hello-docker-action@v1
      with:
        who-to-greet: "Soumya Ranjan"
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"